// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: connector.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStatus int32

const (
	CheckStatus_CHECK_STATUS_UNSPECIFIED CheckStatus = 0
	CheckStatus_CHECK_STATUS_SUCCESS     CheckStatus = 1
	CheckStatus_CHECK_STATUS_FAILED      CheckStatus = 2
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "CHECK_STATUS_UNSPECIFIED",
		1: "CHECK_STATUS_SUCCESS",
		2: "CHECK_STATUS_FAILED",
	}
	CheckStatus_value = map[string]int32{
		"CHECK_STATUS_UNSPECIFIED": 0,
		"CHECK_STATUS_SUCCESS":     1,
		"CHECK_STATUS_FAILED":      2,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_connector_proto_enumTypes[0].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_connector_proto_enumTypes[0]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{0}
}

type SpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecRequest) Reset() {
	*x = SpecRequest{}
	mi := &file_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRequest) ProtoMessage() {}

func (x *SpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRequest.ProtoReflect.Descriptor instead.
func (*SpecRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{0}
}

type SpecResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConfigSchemaJson string                 `protobuf:"bytes,4,opt,name=config_schema_json,json=configSchemaJson,proto3" json:"config_schema_json,omitempty"` // JSON Schema describing expected config fields
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpecResponse) Reset() {
	*x = SpecResponse{}
	mi := &file_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecResponse) ProtoMessage() {}

func (x *SpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecResponse.ProtoReflect.Descriptor instead.
func (*SpecResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{1}
}

func (x *SpecResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpecResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SpecResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SpecResponse) GetConfigSchemaJson() string {
	if x != nil {
		return x.ConfigSchemaJson
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CheckStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=kraal.v1.CheckStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetStatus() CheckStatus {
	if x != nil {
		return x.Status
	}
	return CheckStatus_CHECK_STATUS_UNSPECIFIED
}

func (x *CheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// RelationEdge models a directional dependency/lineage edge between entities or fields.
// e.g. Foreign Keys in databases, or Associations in HubSpot CRM (Deal -> Contact).
type RelationEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceEntity  string                 `protobuf:"bytes,1,opt,name=source_entity,json=sourceEntity,proto3" json:"source_entity,omitempty"` // e.g. "public.orders" or "deals"
	SourceField   string                 `protobuf:"bytes,2,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`    // e.g. "customer_id" or "associated_contact_id"
	TargetEntity  string                 `protobuf:"bytes,3,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"` // e.g. "public.customers" or "contacts"
	TargetField   string                 `protobuf:"bytes,4,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"`    // e.g. "id" or "hs_object_id"
	RelationType  string                 `protobuf:"bytes,5,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"` // e.g. "FOREIGN_KEY", "ASSOCIATION", "VIEW_DEPENDENCY"
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationEdge) Reset() {
	*x = RelationEdge{}
	mi := &file_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationEdge) ProtoMessage() {}

func (x *RelationEdge) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationEdge.ProtoReflect.Descriptor instead.
func (*RelationEdge) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{5}
}

func (x *RelationEdge) GetSourceEntity() string {
	if x != nil {
		return x.SourceEntity
	}
	return ""
}

func (x *RelationEdge) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

func (x *RelationEdge) GetTargetEntity() string {
	if x != nil {
		return x.TargetEntity
	}
	return ""
}

func (x *RelationEdge) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

func (x *RelationEdge) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *RelationEdge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// FieldMetadata represents structured attribute/column metadata of an entity.
type FieldMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	NativeType    string                 `protobuf:"bytes,3,opt,name=native_type,json=nativeType,proto3" json:"native_type,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,4,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	IsNullable    bool                   `protobuf:"varint,5,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMetadata) Reset() {
	*x = FieldMetadata{}
	mi := &file_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMetadata) ProtoMessage() {}

func (x *FieldMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMetadata.ProtoReflect.Descriptor instead.
func (*FieldMetadata) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{6}
}

func (x *FieldMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldMetadata) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *FieldMetadata) GetNativeType() string {
	if x != nil {
		return x.NativeType
	}
	return ""
}

func (x *FieldMetadata) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *FieldMetadata) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *FieldMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StreamSchema struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                         // Entity/table/object name (e.g. "public.users", "contacts")
	PrimaryKeys        []string               `protobuf:"bytes,2,rep,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`                        // Primary key or unique identifier field names
	JsonSchema         string                 `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`                           // JSON Schema representation of the entity
	SupportedSyncModes []string               `protobuf:"bytes,4,rep,name=supported_sync_modes,json=supportedSyncModes,proto3" json:"supported_sync_modes,omitempty"` // e.g. ["METADATA", "LINEAGE"]
	Fields             []*FieldMetadata       `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`                                                     // Structured field/column definitions
	Relations          []*RelationEdge        `protobuf:"bytes,6,rep,name=relations,proto3" json:"relations,omitempty"`                                               // Outgoing lineage edges from this entity
	EntityType         string                 `protobuf:"bytes,7,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                           // e.g. "TABLE", "VIEW", "CRM_OBJECT", "CUSTOM_OBJECT"
	Description        string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamSchema) Reset() {
	*x = StreamSchema{}
	mi := &file_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSchema) ProtoMessage() {}

func (x *StreamSchema) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSchema.ProtoReflect.Descriptor instead.
func (*StreamSchema) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{7}
}

func (x *StreamSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamSchema) GetPrimaryKeys() []string {
	if x != nil {
		return x.PrimaryKeys
	}
	return nil
}

func (x *StreamSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *StreamSchema) GetSupportedSyncModes() []string {
	if x != nil {
		return x.SupportedSyncModes
	}
	return nil
}

func (x *StreamSchema) GetFields() []*FieldMetadata {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *StreamSchema) GetRelations() []*RelationEdge {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *StreamSchema) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *StreamSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamSchema        `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	Relations     []*RelationEdge        `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"` // Cross-entity lineage relationships
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverResponse) GetStreams() []*StreamSchema {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *DiscoverResponse) GetRelations() []*RelationEdge {
	if x != nil {
		return x.Relations
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	StreamName    string                 `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	CursorField   string                 `protobuf:"bytes,3,opt,name=cursor_field,json=cursorField,proto3" json:"cursor_field,omitempty"`
	CursorValue   string                 `protobuf:"bytes,4,opt,name=cursor_value,json=cursorValue,proto3" json:"cursor_value,omitempty"` // Starting cursor for incremental sync
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // Optional row limit (0 = no limit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{9}
}

func (x *ReadRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ReadRequest) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *ReadRequest) GetCursorField() string {
	if x != nil {
		return x.CursorField
	}
	return ""
}

func (x *ReadRequest) GetCursorValue() string {
	if x != nil {
		return x.CursorValue
	}
	return ""
}

func (x *ReadRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecordEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Stream         string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	EmittedAt      string                 `protobuf:"bytes,3,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`    // RFC3339 timestamp
	DataJson       []byte                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`       // Metadata payload encoded as JSON
	Cursor         string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`                           // Cursor value for state tracking
	RecordType     string                 `protobuf:"bytes,6,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // "ENTITY", "RELATION", "METADATA"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordEnvelope) Reset() {
	*x = RecordEnvelope{}
	mi := &file_connector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEnvelope) ProtoMessage() {}

func (x *RecordEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEnvelope.ProtoReflect.Descriptor instead.
func (*RecordEnvelope) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{10}
}

func (x *RecordEnvelope) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *RecordEnvelope) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *RecordEnvelope) GetEmittedAt() string {
	if x != nil {
		return x.EmittedAt
	}
	return ""
}

func (x *RecordEnvelope) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *RecordEnvelope) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RecordEnvelope) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

type WriteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecordsWritten int64                  `protobuf:"varint,1,opt,name=records_written,json=recordsWritten,proto3" json:"records_written,omitempty"`
	RecordsFailed  int64                  `protobuf:"varint,2,opt,name=records_failed,json=recordsFailed,proto3" json:"records_failed,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_connector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{11}
}

func (x *WriteResponse) GetRecordsWritten() int64 {
	if x != nil {
		return x.RecordsWritten
	}
	return 0
}

func (x *WriteResponse) GetRecordsFailed() int64 {
	if x != nil {
		return x.RecordsFailed
	}
	return 0
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_connector_proto protoreflect.FileDescriptor

const file_connector_proto_rawDesc = "" +
	"\n" +
	"\x0fconnector.proto\x12\bkraal.v1\"\r\n" +
	"\vSpecRequest\"\x8c\x01\n" +
	"\fSpecResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x12config_schema_json\x18\x04 \x01(\tR\x10configSchemaJson\"/\n" +
	"\fCheckRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"X\n" +
	"\rCheckResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.kraal.v1.CheckStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x0fDiscoverRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"\xe5\x01\n" +
	"\fRelationEdge\x12#\n" +
	"\rsource_entity\x18\x01 \x01(\tR\fsourceEntity\x12!\n" +
	"\fsource_field\x18\x02 \x01(\tR\vsourceField\x12#\n" +
	"\rtarget_entity\x18\x03 \x01(\tR\ftargetEntity\x12!\n" +
	"\ftarget_field\x18\x04 \x01(\tR\vtargetField\x12#\n" +
	"\rrelation_type\x18\x05 \x01(\tR\frelationType\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xca\x01\n" +
	"\rFieldMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1f\n" +
	"\vnative_type\x18\x03 \x01(\tR\n" +
	"nativeType\x12$\n" +
	"\x0eis_primary_key\x18\x04 \x01(\bR\fisPrimaryKey\x12\x1f\n" +
	"\vis_nullable\x18\x05 \x01(\bR\n" +
	"isNullable\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xc2\x02\n" +
	"\fStreamSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fprimary_keys\x18\x02 \x03(\tR\vprimaryKeys\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\x120\n" +
	"\x14supported_sync_modes\x18\x04 \x03(\tR\x12supportedSyncModes\x12/\n" +
	"\x06fields\x18\x05 \x03(\v2\x17.kraal.v1.FieldMetadataR\x06fields\x124\n" +
	"\trelations\x18\x06 \x03(\v2\x16.kraal.v1.RelationEdgeR\trelations\x12\x1f\n" +
	"\ventity_type\x18\a \x01(\tR\n" +
	"entityType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"z\n" +
	"\x10DiscoverResponse\x120\n" +
	"\astreams\x18\x01 \x03(\v2\x16.kraal.v1.StreamSchemaR\astreams\x124\n" +
	"\trelations\x18\x02 \x03(\v2\x16.kraal.v1.RelationEdgeR\trelations\"\xab\x01\n" +
	"\vReadRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\x12\x1f\n" +
	"\vstream_name\x18\x02 \x01(\tR\n" +
	"streamName\x12!\n" +
	"\fcursor_field\x18\x03 \x01(\tR\vcursorField\x12!\n" +
	"\fcursor_value\x18\x04 \x01(\tR\vcursorValue\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\"\xc6\x01\n" +
	"\x0eRecordEnvelope\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12\x1d\n" +
	"\n" +
	"emitted_at\x18\x03 \x01(\tR\temittedAt\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\fR\bdataJson\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12\x1f\n" +
	"\vrecord_type\x18\x06 \x01(\tR\n" +
	"recordType\"y\n" +
	"\rWriteResponse\x12'\n" +
	"\x0frecords_written\x18\x01 \x01(\x03R\x0erecordsWritten\x12%\n" +
	"\x0erecords_failed\x18\x02 \x01(\x03R\rrecordsFailed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*^\n" +
	"\vCheckStatus\x12\x1c\n" +
	"\x18CHECK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CHECK_STATUS_SUCCESS\x10\x01\x12\x17\n" +
	"\x13CHECK_STATUS_FAILED\x10\x022\xbf\x02\n" +
	"\x10ConnectorService\x125\n" +
	"\x04Spec\x12\x15.kraal.v1.SpecRequest\x1a\x16.kraal.v1.SpecResponse\x128\n" +
	"\x05Check\x12\x16.kraal.v1.CheckRequest\x1a\x17.kraal.v1.CheckResponse\x12A\n" +
	"\bDiscover\x12\x19.kraal.v1.DiscoverRequest\x1a\x1a.kraal.v1.DiscoverResponse\x129\n" +
	"\x04Read\x12\x15.kraal.v1.ReadRequest\x1a\x18.kraal.v1.RecordEnvelope0\x01\x12<\n" +
	"\x05Write\x12\x18.kraal.v1.RecordEnvelope\x1a\x17.kraal.v1.WriteResponse(\x01B7Z5github.com/radicelle/kraal/pkg/protocol/v1;protocolv1b\x06proto3"

var (
	file_connector_proto_rawDescOnce sync.Once
	file_connector_proto_rawDescData []byte
)

func file_connector_proto_rawDescGZIP() []byte {
	file_connector_proto_rawDescOnce.Do(func() {
		file_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connector_proto_rawDesc), len(file_connector_proto_rawDesc)))
	})
	return file_connector_proto_rawDescData
}

var file_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_connector_proto_goTypes = []any{
	(CheckStatus)(0),         // 0: kraal.v1.CheckStatus
	(*SpecRequest)(nil),      // 1: kraal.v1.SpecRequest
	(*SpecResponse)(nil),     // 2: kraal.v1.SpecResponse
	(*CheckRequest)(nil),     // 3: kraal.v1.CheckRequest
	(*CheckResponse)(nil),    // 4: kraal.v1.CheckResponse
	(*DiscoverRequest)(nil),  // 5: kraal.v1.DiscoverRequest
	(*RelationEdge)(nil),     // 6: kraal.v1.RelationEdge
	(*FieldMetadata)(nil),    // 7: kraal.v1.FieldMetadata
	(*StreamSchema)(nil),     // 8: kraal.v1.StreamSchema
	(*DiscoverResponse)(nil), // 9: kraal.v1.DiscoverResponse
	(*ReadRequest)(nil),      // 10: kraal.v1.ReadRequest
	(*RecordEnvelope)(nil),   // 11: kraal.v1.RecordEnvelope
	(*WriteResponse)(nil),    // 12: kraal.v1.WriteResponse
}
var file_connector_proto_depIdxs = []int32{
	0,  // 0: kraal.v1.CheckResponse.status:type_name -> kraal.v1.CheckStatus
	7,  // 1: kraal.v1.StreamSchema.fields:type_name -> kraal.v1.FieldMetadata
	6,  // 2: kraal.v1.StreamSchema.relations:type_name -> kraal.v1.RelationEdge
	8,  // 3: kraal.v1.DiscoverResponse.streams:type_name -> kraal.v1.StreamSchema
	6,  // 4: kraal.v1.DiscoverResponse.relations:type_name -> kraal.v1.RelationEdge
	1,  // 5: kraal.v1.ConnectorService.Spec:input_type -> kraal.v1.SpecRequest
	3,  // 6: kraal.v1.ConnectorService.Check:input_type -> kraal.v1.CheckRequest
	5,  // 7: kraal.v1.ConnectorService.Discover:input_type -> kraal.v1.DiscoverRequest
	10, // 8: kraal.v1.ConnectorService.Read:input_type -> kraal.v1.ReadRequest
	11, // 9: kraal.v1.ConnectorService.Write:input_type -> kraal.v1.RecordEnvelope
	2,  // 10: kraal.v1.ConnectorService.Spec:output_type -> kraal.v1.SpecResponse
	4,  // 11: kraal.v1.ConnectorService.Check:output_type -> kraal.v1.CheckResponse
	9,  // 12: kraal.v1.ConnectorService.Discover:output_type -> kraal.v1.DiscoverResponse
	11, // 13: kraal.v1.ConnectorService.Read:output_type -> kraal.v1.RecordEnvelope
	12, // 14: kraal.v1.ConnectorService.Write:output_type -> kraal.v1.WriteResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_connector_proto_init() }
func file_connector_proto_init() {
	if File_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connector_proto_rawDesc), len(file_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connector_proto_goTypes,
		DependencyIndexes: file_connector_proto_depIdxs,
		EnumInfos:         file_connector_proto_enumTypes,
		MessageInfos:      file_connector_proto_msgTypes,
	}.Build()
	File_connector_proto = out.File
	file_connector_proto_goTypes = nil
	file_connector_proto_depIdxs = nil
}
