// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: connector.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStatus int32

const (
	CheckStatus_CHECK_STATUS_UNSPECIFIED CheckStatus = 0
	CheckStatus_CHECK_STATUS_SUCCESS     CheckStatus = 1
	CheckStatus_CHECK_STATUS_FAILED      CheckStatus = 2
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "CHECK_STATUS_UNSPECIFIED",
		1: "CHECK_STATUS_SUCCESS",
		2: "CHECK_STATUS_FAILED",
	}
	CheckStatus_value = map[string]int32{
		"CHECK_STATUS_UNSPECIFIED": 0,
		"CHECK_STATUS_SUCCESS":     1,
		"CHECK_STATUS_FAILED":      2,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_connector_proto_enumTypes[0].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_connector_proto_enumTypes[0]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{0}
}

type SpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecRequest) Reset() {
	*x = SpecRequest{}
	mi := &file_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRequest) ProtoMessage() {}

func (x *SpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRequest.ProtoReflect.Descriptor instead.
func (*SpecRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{0}
}

type SpecResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConfigSchemaJson string                 `protobuf:"bytes,4,opt,name=config_schema_json,json=configSchemaJson,proto3" json:"config_schema_json,omitempty"` // JSON Schema describing expected config fields
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpecResponse) Reset() {
	*x = SpecResponse{}
	mi := &file_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecResponse) ProtoMessage() {}

func (x *SpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecResponse.ProtoReflect.Descriptor instead.
func (*SpecResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{1}
}

func (x *SpecResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpecResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SpecResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SpecResponse) GetConfigSchemaJson() string {
	if x != nil {
		return x.ConfigSchemaJson
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CheckStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=kraal.v1.CheckStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetStatus() CheckStatus {
	if x != nil {
		return x.Status
	}
	return CheckStatus_CHECK_STATUS_UNSPECIFIED
}

func (x *CheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type StreamSchema struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                         // Table or stream name (e.g. "users")
	PrimaryKeys        []string               `protobuf:"bytes,2,rep,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`                        // Primary key field names
	JsonSchema         string                 `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`                           // Column definitions & JSON types
	SupportedSyncModes []string               `protobuf:"bytes,4,rep,name=supported_sync_modes,json=supportedSyncModes,proto3" json:"supported_sync_modes,omitempty"` // e.g. ["FULL_REFRESH", "INCREMENTAL"]
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamSchema) Reset() {
	*x = StreamSchema{}
	mi := &file_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSchema) ProtoMessage() {}

func (x *StreamSchema) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSchema.ProtoReflect.Descriptor instead.
func (*StreamSchema) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{5}
}

func (x *StreamSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamSchema) GetPrimaryKeys() []string {
	if x != nil {
		return x.PrimaryKeys
	}
	return nil
}

func (x *StreamSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *StreamSchema) GetSupportedSyncModes() []string {
	if x != nil {
		return x.SupportedSyncModes
	}
	return nil
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamSchema        `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoverResponse) GetStreams() []*StreamSchema {
	if x != nil {
		return x.Streams
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	StreamName    string                 `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	CursorField   string                 `protobuf:"bytes,3,opt,name=cursor_field,json=cursorField,proto3" json:"cursor_field,omitempty"`
	CursorValue   string                 `protobuf:"bytes,4,opt,name=cursor_value,json=cursorValue,proto3" json:"cursor_value,omitempty"` // Starting cursor for incremental sync
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // Optional row limit (0 = no limit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ReadRequest) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *ReadRequest) GetCursorField() string {
	if x != nil {
		return x.CursorField
	}
	return ""
}

func (x *ReadRequest) GetCursorValue() string {
	if x != nil {
		return x.CursorValue
	}
	return ""
}

func (x *ReadRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecordEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Stream         string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	EmittedAt      string                 `protobuf:"bytes,3,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"` // RFC3339 timestamp
	DataJson       []byte                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`    // Record payload encoded as JSON
	Cursor         string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`                        // Cursor value for state tracking
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordEnvelope) Reset() {
	*x = RecordEnvelope{}
	mi := &file_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEnvelope) ProtoMessage() {}

func (x *RecordEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEnvelope.ProtoReflect.Descriptor instead.
func (*RecordEnvelope) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{8}
}

func (x *RecordEnvelope) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *RecordEnvelope) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *RecordEnvelope) GetEmittedAt() string {
	if x != nil {
		return x.EmittedAt
	}
	return ""
}

func (x *RecordEnvelope) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *RecordEnvelope) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type WriteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecordsWritten int64                  `protobuf:"varint,1,opt,name=records_written,json=recordsWritten,proto3" json:"records_written,omitempty"`
	RecordsFailed  int64                  `protobuf:"varint,2,opt,name=records_failed,json=recordsFailed,proto3" json:"records_failed,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{9}
}

func (x *WriteResponse) GetRecordsWritten() int64 {
	if x != nil {
		return x.RecordsWritten
	}
	return 0
}

func (x *WriteResponse) GetRecordsFailed() int64 {
	if x != nil {
		return x.RecordsFailed
	}
	return 0
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_connector_proto protoreflect.FileDescriptor

const file_connector_proto_rawDesc = "" +
	"\n" +
	"\x0fconnector.proto\x12\bkraal.v1\"\r\n" +
	"\vSpecRequest\"\x8c\x01\n" +
	"\fSpecResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x12config_schema_json\x18\x04 \x01(\tR\x10configSchemaJson\"/\n" +
	"\fCheckRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"X\n" +
	"\rCheckResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.kraal.v1.CheckStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x0fDiscoverRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"\x98\x01\n" +
	"\fStreamSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fprimary_keys\x18\x02 \x03(\tR\vprimaryKeys\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\x120\n" +
	"\x14supported_sync_modes\x18\x04 \x03(\tR\x12supportedSyncModes\"D\n" +
	"\x10DiscoverResponse\x120\n" +
	"\astreams\x18\x01 \x03(\v2\x16.kraal.v1.StreamSchemaR\astreams\"\xab\x01\n" +
	"\vReadRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\x12\x1f\n" +
	"\vstream_name\x18\x02 \x01(\tR\n" +
	"streamName\x12!\n" +
	"\fcursor_field\x18\x03 \x01(\tR\vcursorField\x12!\n" +
	"\fcursor_value\x18\x04 \x01(\tR\vcursorValue\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\"\xa5\x01\n" +
	"\x0eRecordEnvelope\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12\x1d\n" +
	"\n" +
	"emitted_at\x18\x03 \x01(\tR\temittedAt\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\fR\bdataJson\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"y\n" +
	"\rWriteResponse\x12'\n" +
	"\x0frecords_written\x18\x01 \x01(\x03R\x0erecordsWritten\x12%\n" +
	"\x0erecords_failed\x18\x02 \x01(\x03R\rrecordsFailed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*^\n" +
	"\vCheckStatus\x12\x1c\n" +
	"\x18CHECK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CHECK_STATUS_SUCCESS\x10\x01\x12\x17\n" +
	"\x13CHECK_STATUS_FAILED\x10\x022\xbf\x02\n" +
	"\x10ConnectorService\x125\n" +
	"\x04Spec\x12\x15.kraal.v1.SpecRequest\x1a\x16.kraal.v1.SpecResponse\x128\n" +
	"\x05Check\x12\x16.kraal.v1.CheckRequest\x1a\x17.kraal.v1.CheckResponse\x12A\n" +
	"\bDiscover\x12\x19.kraal.v1.DiscoverRequest\x1a\x1a.kraal.v1.DiscoverResponse\x129\n" +
	"\x04Read\x12\x15.kraal.v1.ReadRequest\x1a\x18.kraal.v1.RecordEnvelope0\x01\x12<\n" +
	"\x05Write\x12\x18.kraal.v1.RecordEnvelope\x1a\x17.kraal.v1.WriteResponse(\x01B7Z5github.com/radicelle/kraal/pkg/protocol/v1;protocolv1b\x06proto3"

var (
	file_connector_proto_rawDescOnce sync.Once
	file_connector_proto_rawDescData []byte
)

func file_connector_proto_rawDescGZIP() []byte {
	file_connector_proto_rawDescOnce.Do(func() {
		file_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connector_proto_rawDesc), len(file_connector_proto_rawDesc)))
	})
	return file_connector_proto_rawDescData
}

var file_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_connector_proto_goTypes = []any{
	(CheckStatus)(0),         // 0: kraal.v1.CheckStatus
	(*SpecRequest)(nil),      // 1: kraal.v1.SpecRequest
	(*SpecResponse)(nil),     // 2: kraal.v1.SpecResponse
	(*CheckRequest)(nil),     // 3: kraal.v1.CheckRequest
	(*CheckResponse)(nil),    // 4: kraal.v1.CheckResponse
	(*DiscoverRequest)(nil),  // 5: kraal.v1.DiscoverRequest
	(*StreamSchema)(nil),     // 6: kraal.v1.StreamSchema
	(*DiscoverResponse)(nil), // 7: kraal.v1.DiscoverResponse
	(*ReadRequest)(nil),      // 8: kraal.v1.ReadRequest
	(*RecordEnvelope)(nil),   // 9: kraal.v1.RecordEnvelope
	(*WriteResponse)(nil),    // 10: kraal.v1.WriteResponse
}
var file_connector_proto_depIdxs = []int32{
	0,  // 0: kraal.v1.CheckResponse.status:type_name -> kraal.v1.CheckStatus
	6,  // 1: kraal.v1.DiscoverResponse.streams:type_name -> kraal.v1.StreamSchema
	1,  // 2: kraal.v1.ConnectorService.Spec:input_type -> kraal.v1.SpecRequest
	3,  // 3: kraal.v1.ConnectorService.Check:input_type -> kraal.v1.CheckRequest
	5,  // 4: kraal.v1.ConnectorService.Discover:input_type -> kraal.v1.DiscoverRequest
	8,  // 5: kraal.v1.ConnectorService.Read:input_type -> kraal.v1.ReadRequest
	9,  // 6: kraal.v1.ConnectorService.Write:input_type -> kraal.v1.RecordEnvelope
	2,  // 7: kraal.v1.ConnectorService.Spec:output_type -> kraal.v1.SpecResponse
	4,  // 8: kraal.v1.ConnectorService.Check:output_type -> kraal.v1.CheckResponse
	7,  // 9: kraal.v1.ConnectorService.Discover:output_type -> kraal.v1.DiscoverResponse
	9,  // 10: kraal.v1.ConnectorService.Read:output_type -> kraal.v1.RecordEnvelope
	10, // 11: kraal.v1.ConnectorService.Write:output_type -> kraal.v1.WriteResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_connector_proto_init() }
func file_connector_proto_init() {
	if File_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connector_proto_rawDesc), len(file_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connector_proto_goTypes,
		DependencyIndexes: file_connector_proto_depIdxs,
		EnumInfos:         file_connector_proto_enumTypes,
		MessageInfos:      file_connector_proto_msgTypes,
	}.Build()
	File_connector_proto = out.File
	file_connector_proto_goTypes = nil
	file_connector_proto_depIdxs = nil
}
